# Name: Ahmed Mohamed Makram

# Task 2 : Color Identification

# Institute name :THE SPARKS FOUNDATION

In [1]:
#imports
#cv2 (opencv) for image processing
#pandas for dealing with dataset 
import cv2   
import pandas as pd

In [2]:
#read the dataset
df = pd.read_csv('colors.csv')
#show sample of the dataset 
df.head()
#color.csv contains color , color name ,hex values and [R , G , B] values of the color

     air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
0   air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
1  air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
2       alabama_crimson        Alabama Crimson  #a32638  163   38   56
3            alice_blue             Alice Blue  #f0f8ff  240  248  255
4      alizarin_crimson       Alizarin Crimson  #e32636  227   38   54

In [3]:
#idx list contains the new names of the columns in the color dataset
idx = ['color', 'color_name', 'hex_value', 'R', 'G', 'B']
#change the names of the columns in dataset
df = pd.read_csv('colors.csv', names=idx)
df

                    color             color_name hex_value    R    G    B
0      air_force_blue_raf   Air Force Blue (Raf)   #5d8aa8   93  138  168
1     air_force_blue_usaf  Air Force Blue (Usaf)   #00308f    0   48  143
2    air_superiority_blue   Air Superiority Blue   #72a0c1  114  160  193
3         alabama_crimson        Alabama Crimson   #a32638  163   38   56
4              alice_blue             Alice Blue   #f0f8ff  240  248  255
..                    ...                    ...       ...  ...  ...  ...
860         yellow_orange          Yellow Orange   #ffae42  255  174   66
861        yellow_process       Yellow (Process)   #ffef00  255  239    0
862            yellow_ryb           Yellow (Ryb)   #fefe33  254  254   51
863                zaffre                 Zaffre   #0014a8    0   20  168
864     zinnwaldite_brown      Zinnwaldite Brown   #2c1608   44   22    8

[865 rows x 6 columns]

In [4]:
isClicked = False 
r = g = b = x_pos = y_pos = 0

# Define Draw Function

In [5]:
#Draw Function
  #Draw function works with the callback function "setMouseCallback"
  #input : event , x ,y ,flag , parameters("setMouseCallback" outputs)
  # mouse event is "left button double click" 
  #when event occurs the the pixel value is assigned to be passed ...
  #to the "match_image_by_color" function to get the pixel color 
def draw(event, x, y, flags, parameters):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        global isClicked, r, g, b, x_pos, y_pos
        isClicked = True
        x_pos = x
        y_pos = y
        b, g, r = img[y, x]
        r = int(r)
        g = int(g)
        b = int(b)

# get the color name

In [6]:
#input  : RGB pixel values
#output : the aprroximate color from the dataset .
#         minimum difference between the pixel  ...
#         RGB values and the colors in the dataset .
def match_image_by_color(R, G, B):
    minimum = 1e5
    for i in range(len(df)):
        diff = abs(R-int(df.loc[i, 'R']))+abs(G-int(df.loc[i, 'G']))+abs(B-int(df.loc[i, 'B']))
        if diff<=minimum:
            minimum = diff
            color_name = df.loc[i, 'color_name']
    return color_name

# Read The image

In [7]:
img = cv2.imread('img.jpg')
img = cv2.resize(img, (800,600))

In [ ]:
#create window with name 'image'
cv2.namedWindow('image')

#setMouseCallback : Callback function for mouse events.
cv2.setMouseCallback('image', draw)

#go through infinite loop 
 #if event occured 
    #1-create rectangle paced in (20,20), (600,60) co_ordinates
    #2-create text containing color name and RGB values
    #3-put the text into the colored ractangle inside the image
    #4-if the pixel is white put the text black
    #5-if escape button is pressed exit the loop and close all windows 
while True:
    cv2.imshow('image', img)
    if isClicked:
        cv2.rectangle(img, (20,20), (600,60), (b,g,r), -1)
        txt = match_image_by_color(r,g,b) + ' R=' + str(r) + ' G=' + str(g) + ' B=' + str(b)
        cv2.putText(img, txt, (50,50), 2,0.8, (255,255,255),2,cv2.LINE_AA)
        if r+g+b >=600:
            cv2.putText(img, txt, (50,50), 2,0.8, (0,0,0),2,cv2.LINE_AA)
    if cv2.waitKey(20) & 0xFF == 27:
        break

#close image window
cv2.destroyAllWindows()